name: Test pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Install packages
        run: bun install
      - name: Run tests
        run: bun test:ci

  security:
    name: Security checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Install packages
        run: bun install

  docker-build:
    name: Check docker image builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the Docker image but dont deploy it
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: test-build
